### ISSUE TITLE
[本地部署] 列表类型显示错误

### ISSUE THREAD

**Issue by ackness** [GaiZhenbiao/ChuanhuChatGPT#235]
### 错误描述
如题, markdwon 格式的列表类型超出对话框

### 复现操作
提问, 比如如下问题
`用markdown 的列表列出把大象装进冰箱的步骤`
`用markdown 的有序列表列出把大象装进冰箱的步骤`

### 错误截图
<img width="891" alt="image" src="https://user-images.githubusercontent.com/19150500/226397713-0f5a2164-a2d9-4965-aeb3-d479b0f2f8f7.png">

**Comment by Keldos-Li** [comment]
emm 是个已知问题。不过还是感谢反馈🎉
~~（总能用CSS干掉的……）~~

**Comment by Keldos-Li** [comment]
合并同类issue

### 有序列表序号显示错误
_Originally reported by @bentwnghk in #243_
![listing](https://user-images.githubusercontent.com/101241940/226507303-afaa7935-3598-4b91-83f9-f7c2ed05485f.png)

应该是: 1, 2, 3, 4, 5 现在是: 1, 1, 1, 1, 1

<hr>

能够复现的已知问题的。

**Comment by Keldos-Li** [comment]
Fixed by:
- fix: 修改parse_text，删去列表中可能的空行 bf090a322136bcf2003afedd0670b930d6670787 ([Keldos](https://github.com/Keldos-Li))
- 调整CSS，使得有序列表和无序列表可以被正常显示 0baaa020db01a2cfce610ae4db99ae9ce9a2373d ([Chuanhu](https://github.com/GaiZhenbiao))
- hotfix: 修复下拉列表显示, fix #257 7e1158640776ba88833e2cd96568ccd0ad294504 ([Keldos](https://github.com/Keldos-Li))
- 大幅度改进了输入输出解析。 90d39c30417719e9b819b0ea78f7c62d7646441a ([Chuanhu](https://github.com/GaiZhenbiao))
- feat: 调整列表样式 e071cb7a3703575fd04ea2276b7a3aff07a0aa36 ([Keldos](https://github.com/Keldos-Li))
